# Generated by Django 4.1.4 on 2022-12-17 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exibicao', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.PositiveSmallIntegerField(default=1)),
                ('area', models.PositiveBigIntegerField(default=100)),
                ('logradouro', models.CharField(max_length=500)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_venda', models.DecimalField(decimal_places=2, default=None, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnexoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=None)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='imoveisapiapp.imovel')),
            ],
        ),
    ]
