# Generated by Django 4.1.4 on 2022-12-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveisapiapp', '0002_alter_anexoimovel_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='area',
            field=models.FloatField(),
        ),
    ]
