# Generated by Django 4.1.4 on 2022-12-22 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveisapiapp', '0003_alter_imovel_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='tipo',
        ),
    ]
